apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - backup-cronjob.yaml
  - backup-pvc.yaml

configMapGenerator:
  - name: backup-scripts
    files:
      - backup.sh
    options:
      labels:
        app.kubernetes.io/component: backup