# GCP Provider for Crossplane
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
  annotations:
    meta.crossplane.io/maintainer: "Upbound"
    meta.crossplane.io/source: "github.com/upbound/provider-gcp"
    meta.crossplane.io/license: "Apache-2.0"
    meta.crossplane.io/description: "GCP Provider for Crossplane"
spec:
  package: xpkg.upbound.io/upbound/provider-gcp:v0.41.0
  controllerConfigRef:
    name: provider-gcp-config
---
# Controller configuration for GCP provider
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-gcp-config
  annotations:
    iam.gke.io/gcp-service-account: "crossplane@PROJECT_ID.iam.gserviceaccount.com"
spec:
  podSecurityContext:
    fsGroup: 2000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    - name: GOOGLE_PROJECT
      value: "PROJECT_ID"