apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - pod-security-policy.yaml
  - network-policy-default.yaml

patches:
  # Add security context to all pods
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
  
  # Add pod security standards
  - target:
      kind: Namespace
      name: ".*"
    patch: |-
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: restricted
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit
        value: restricted
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: restricted