apiVersion: v2
name: dora-metrics
description: A Helm chart for DORA metrics collection and analysis
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - dora
  - metrics
  - devops
  - monitoring
home: https://github.com/jefrnc/devops-playbook
sources:
  - https://github.com/jefrnc/devops-playbook
maintainers:
  - name: Platform Team
    email: platform@example.com
icon: https://raw.githubusercontent.com/jefrnc/devops-playbook/main/assets/logo.png
annotations:
  category: Monitoring
  artifacthub.io/changes: |
    - kind: added
      description: Initial release with DORA metrics collection
  artifacthub.io/crds: |
    - kind: DORAMetric
      version: v1
      description: Custom resource for DORA metrics configuration
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: "Full Lifecycle"
  artifacthub.io/prerelease: "false"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache
  - name: prometheus
    version: "19.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    tags:
      - monitoring