AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table to store deployment information'

Resources:
  DeploymentStatusTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'DeploymentStatus'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'timestamp'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'timestamp'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: 'timestamp'
        Enabled: true
