apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dora-operator
  labels:
    app: dora-operator
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: dora-operator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dora-dashboard
  labels:
    app: dora-dashboard
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: dora-dashboard
  endpoints:
  - port: http
    interval: 30s
    path: /metrics