apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-operator
  labels:
    app.kubernetes.io/name: dora-operator
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-metrics-collector
  labels:
    app.kubernetes.io/name: dora-metrics-collector
    app.kubernetes.io/component: collector
automountServiceAccountToken: true